apiVersion: kaap.oss.datastax.com/v1beta1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
  namespace: pulsar
spec:
  global:
    name: pulsar
  zookeeper:
    replicas: 3
  bookkeeper:
    replicas: 3
  broker:
    replicas: 3
  proxy:
    replicas: 1
  autorecovery:
    replicas: 1
  bastion:
    replicas: 1
  functionsWorker:
    replicas: 1