kaap:
  cluster:
    create: true
    spec:
      global:
        name: pulsar
        image: apachepulsar/pulsar:3.0.0
        restartOnConfigMapChange: true
        tls:
          enabled: true
          zookeeper:
            enabled: true
            secretName: zk-tls
          bookkeeper:
            enabled: true
            secretName: bk-tls
          autorecovery:
            enabled: true
            secretName: autorecovery-tls
          proxy:
            enabled: true
            enabledWithBroker: true
            secretName: proxy-tls
          broker:
            enabled: true
            secretName: broker-tls
          functionsWorker:
            enabled: true
            enabledWithBroker: true
            secretName: fnw-tls
          certProvisioner:
            selfSigned:
              enabled: true
              perComponent: true
              zookeeper:
                generate: true
              broker:
                generate: true
              bookkeeper:
                generate: true
              autorecovery:
                generate: true
              proxy:
                generate: true
              functionsWorker:
                generate: true
      zookeeper:
        replicas: 1
        dataVolume:
          name: data
          size: 100M
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      bookkeeper:
        replicas: 1
        volumes:
          journal:
            size: 1Gi
          ledgers:
            size: 1Gi
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      broker:
        replicas: 1
        config:
          managedLedgerDefaultAckQuorum: "1"
          managedLedgerDefaultEnsembleSize: "1"
          managedLedgerDefaultWriteQuorum: "1"
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      proxy:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
        webSocket:
          resources:
            requests:
              cpu: "0.2"
              memory: "128Mi"
      autorecovery:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      bastion:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      functionsWorker:
        replicas: 1
        runtime: kubernetes
        config:
          pulsarFunctionsCluster: pulsar
          pulsarServiceUrl: "pulsar+ssl://pulsar-broker.pulsar.svc.cluster.local:6651"
          # pulsarServiceUrl: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
          # pulsarAdminUrl: "http://pulsar-function.pulsar.svc.cluster.local:6750"
          pulsarAdminUrl: "https://pulsar-function.pulsar.svc.cluster.local:6751"
          # useTls: false
          # tlsEnabled: false
          kubernetes:
            namespace: pulsar
            submitServiceEnabled: true
          numFunctionPackageReplicas: 1
          functionInstanceMaxResources:
            disk: 10000000000
            ram: 500000000
            cpu: 0.3
          tlsAllowInsecureConnection: true
        resources:
          requests:
            cpu: "0.3"

pulsarGrafanaDashboards:
  enabled: true

kube-prometheus-stack:
  enabled: true
  grafana:
    adminPassword: grafana1